swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Accounts API
      description: API for fetching all user's accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User accounts retrieved successully
          schema:
            $ref: '#/definitions/UserAccounts'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Single Account's transactions API
      description: API for fetching an account's transactions from its accountId
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          description: ID of the account that needs to be retrieved
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User account's transactions retrieved successully
          schema:
            $ref: '#/definitions/UserTransactions'
        '400':
          description: Invalid Fields
        '404':
          description: Unknown {accountId} or {transactionId}
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User single transaction API
      description: API for fetching an account's transaction from its accountId and transactionId
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          description: ID of the account that needs to be retrieved
          required: true
        - in: path
          name: transactionId
          description: ID of the transaction that needs to be retrieved
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/transactionMeta'
        '400':
          description: Invalid Fields
        '404':
          description: Unknown {accountId} or {transactionId}
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User single transaction information udpate API
      description: API for updating an account's transaction from its accountId and transactionId
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          description: ID of the account that needs to be retrieved
          required: true
        - in: path
          name: transactionId
          description: ID of the transaction that needs to be retrieved
          required: true
        - in: body
          name: body
          description: 'Updated transaction information'
          required: true
          schema: 
            $ref: '#/definitions/transactionMeta'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction updated successully
        '400':
          description: Invalid Fields
        '404':
          description: Unknown {accountId} or {transactionId}
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  UserAccounts:
    type: object
    properties:
      accountType:
        type: string
        description: account type -eg. savings, credit card
      accountId:
        type: string
        description: a unique id for the account
      accountBalance:
        type: integer
        description: the amount of money on the account
  UserTransactions:
    type: object
    properties:
      transaction:
        type: object
        properties:
          transactionMeta:
            $ref: "#/definitions/transactionMeta"
  transactionMeta:
    type: object
    properties:
      transactionId:
        type: integer
        description: a unique id for the transaction
      transactionDate:
        type: string
        description: the date of a transaction
      transactionDescription:
        type: string
        description: the description for a transaction
      transactionAmount:
        type: integer
        description: the amount of a transaction
      transactionBalance:
        type: integer
        description: the updated balance after a transaction
      transactionType:
        type: string
        description: the type of a transaction
      transactionCategory:
        type: string
        description: the category of a transaction
      transactionNote:
        type: string
        description: the notes added to a transaction